# -*- coding: utf-8 -*-
"""imorting inbuilt libraries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hh_8GgYfY6KMXtk7Kr3Bdz-S37kkKOMD

### INBUILT LIBRARY

## Defining some random function of Flippping a coin , rolling a dice and picking a student from the list. This is some inbuilt function and libraries that are built in python files in order to flip_coin() , roll_dice(), pick_students(student_list) out of a list in the libraries.
"""

import random

def flip_coin():
    """Returns 'Heads' or 'Tails' randomly."""
    choices = ['Heads', 'Tails']
    return random.choice(choices)

def roll_dice():
    """Returns a random number between 1 and 6."""
    return random.randint(1, 6)

def pick_student(student_list):
    """Picks a random student from a list for a pop quiz."""
    if not student_list:
        return "No students in the list!"
    return random.choice(student_list)


print(flip_coin())
print(roll_dice())
student_list = [1,2,3,4,5]
print(pick_student(student_list))

"""
## get_todays_date(): This function returns the current date formatted as a string, for example, 'Monday, January 01, 2024'. It uses date.today() to get the current date and strftime() to format it.

## days_until_birthday(month, day): This function calculates the number of days remaining until a specified birthday. It takes month and day as arguments. If the birthday has already passed in the current year, it calculates the days until the birthday in the next year."""

from datetime import datetime, date

def get_todays_date():
    """Returns today's date as a nice string."""
    today = date.today()
    # Format: Monday, January 01, 2024
    return today.strftime("%A, %B %d, %Y")

def days_until_birthday(month, day):
    """Calculates days left until a birthday this year."""
    today = date.today()
    # Create a date object for the birthday this year
    birthday = date(today.year, month, day)

    # If birthday passed, look at next year
    if birthday < today:
        birthday = date(today.year + 1, month, day)

    delta = birthday - today
    return delta.days

print(get_todays_date())
numberofdays = days_until_birthday(12, 25)
print(numberofdays)

"""
## get_top_winner(votes): This function takes a list of votes (e.g., ['Red', 'Blue', 'Red']) and returns the item that appears most frequently. It uses Counter to count each item and then most_common(1) to get the top winner along with its count.

## count_all_items(items): This function takes a list of items and returns a dictionary where each unique item is a key and its value is the number of times it appeared in the list. For example, count_all_items(['apple', 'banana', 'apple']) would return {'apple': 2, 'banana': 1}."""

from collections import Counter

def get_top_winner(votes):
    """Finds the item with the most votes."""
    # Counter counts elements: {'Red': 2, 'Blue': 3}
    c = Counter(votes)
    # most_common(1) returns a list like [('Blue', 3)]
    return c.most_common(1)[0]

def count_all_items(items):
    """Returns a simple dictionary of counts."""
    return dict(Counter(items))

# Example of how to call get_top_winner with an iterable (list of votes)
common_votes = get_top_winner(['Red', 'Blue', 'Red', 'Green', 'Blue'])
print(common_votes)

count = count_all_items("this","is","where")
print(count)

"""## Certainly! This code uses the collections.Counter class to help with counting items in lists. It defines two functions:

## get_top_winner(votes): This function takes a list of votes (e.g., ['Red', 'Blue', 'Red']) and returns the item that appears most frequently. It uses Counter to count each item and then most_common(1) to get the top winner along with its count.

## count_all_items(items): This function takes a list of items and returns a dictionary where each unique item is a key and its value is the number of times it appeared in the list. For example, count_all_items(['apple', 'banana', 'apple']) would return {'apple': 2, 'banana': 1}.


"""

from collections import Counter

def get_top_winner(votes):
    """Finds the item with the most votes."""
    # Counter counts elements: {'Red': 2, 'Blue': 3}
    c = Counter(votes)
    # most_common(1) returns a list like [('Blue', 3)]
    return c.most_common(1)[0]

def count_all_items(items):
    """Returns a simple dictionary of counts."""
    return dict(Counter(items))


class_votes = ["Blue", "Red", "Blue", "Green", "Red", "Blue"]
lunch_orders = ["Pizza", "Burger", "Pizza", "Salad", "Pizza"]

# 2. Call 'get_top_winner' with the votes list
winner = get_top_winner(class_votes)
print(f"Top Winner Output: {winner}")

# 3. Call 'count_all_items' with the lunch list
counts = count_all_items(lunch_orders)
print(f"All Counts Output: {counts}")